'''
Created on 2013-3-1

@author: yelu01
'''

from mysql.connector.constants import _constants

class EventType(_constants):
    _prefix = ''
    UNKNOWN_EVENT = 0x00
    START_EVENT_V3 = 0x01
    QUERY_EVENT = 0x02
    STOP_EVENT = 0x03
    ROTATE_EVENT = 0x04
    INTVAR_EVENT = 0x05
    LOAD_EVENT = 0x06
    SLAVE_EVENT = 0x07
    CREATE_FILE_EVENT = 0x08
    APPEND_BLOCK_EVENT = 0x09
    EXEC_LOAD_EVENT = 0x0a
    DELETE_FILE_EVENT = 0x0b
    NEW_LOAD_EVENT = 0x0c
    RAND_EVENT = 0x0d
    USER_VAR_EVENT = 0x0e
    FORMAT_DESCRIPTION_EVENT = 0x0f
    XID_EVENT = 0x10
    BEGIN_LOAD_QUERY_EVENT = 0x11
    EXECUTE_LOAD_QUERY_EVENT = 0x12
    TABLE_MAP_EVENT = 0x13
    PRE_GA_DELETE_ROWS_EVENT = 0x14
    PRE_GA_UPDATE_ROWS_EVENT = 0x15
    PRE_GA_WRITE_ROWS_EVENT = 0x16
    DELETE_ROWS_EVENT = 0x19
    UPDATE_ROWS_EVENT = 0x18
    WRITE_ROWS_EVENT = 0x17
    INCIDENT_EVENT = 0x1a
    HEARTBEAT_LOG_EVENT = 0x1b
    
    desc = {
        'UNKNOWN_EVENT' : (0x00, 'UNKNOWN_EVENT'),
        'START_EVENT_V3' : (0x01, 'START_EVENT_V3'),
        'QUERY_EVENT' : (0x02, 'QUERY_EVENT'),
        'STOP_EVENT' : (0x03, 'STOP_EVENT'),
        'ROTATE_EVENT' : (0x04, 'ROTATE_EVENT'),
        'INTVAR_EVENT' : (0x05, 'INTVAR_EVENT'),
        'LOAD_EVENT' : (0x06, 'LOAD_EVENT'),
        'SLAVE_EVENT' : (0x07, 'SLAVE_EVENT'),
        'CREATE_FILE_EVENT' : (0x08, 'CREATE_FILE_EVENT'),
        'APPEND_BLOCK_EVENT' : (0x09, 'APPEND_BLOCK_EVENT'),
        'EXEC_LOAD_EVENT' : (0x0a, 'EXEC_LOAD_EVENT'),
        'DELETE_FILE_EVENT' : (0x0b, 'DELETE_FILE_EVENT'),
        'NEW_LOAD_EVENT' : (0x0c, 'NEW_LOAD_EVENT'),
        'RAND_EVENT' : (0x0d, 'RAND_EVENT'),
        'USER_VAR_EVENT' : (0x0e, 'USER_VAR_EVENT'),
        'FORMAT_DESCRIPTION_EVENT' : (0x0f, 'FORMAT_DESCRIPTION_EVENT'),
        'XID_EVENT' : (0x10, 'XID_EVENT'),
        'BEGIN_LOAD_QUERY_EVENT' : (0x11, 'BEGIN_LOAD_QUERY_EVENT'),
        'EXECUTE_LOAD_QUERY_EVENT' : (0x12, 'EXECUTE_LOAD_QUERY_EVENT'),
        'TABLE_MAP_EVENT' : (0x13, 'TABLE_MAP_EVENT'),
        'PRE_GA_DELETE_ROWS_EVENT' : (0x14, 'PRE_GA_DELETE_ROWS_EVENT'),
        'PRE_GA_UPDATE_ROWS_EVENT' : (0x15, 'PRE_GA_UPDATE_ROWS_EVENT'),
        'PRE_GA_WRITE_ROWS_EVENT' : (0x16, 'PRE_GA_WRITE_ROWS_EVENT'),
        'DELETE_ROWS_EVENT' : (0x19, 'DELETE_ROWS_EVENT'),
        'UPDATE_ROWS_EVENT' : (0x18, 'UPDATE_ROWS_EVENT'),
        'WRITE_ROWS_EVENT' : (0x17, 'WRITE_ROWS_EVENT'),
        'INCIDENT_EVENT' : (0x1a, 'INCIDENT_EVENT'),
        'HEARTBEAT_LOG_EVENT' : (0x1b, 'HEARTBEAT_LOG_EVENT')
    }